/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jenkins_3_sample_java_lib;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
